### ISSUE TITLE
[FEAT] Prototype ability to chain apps through a chat interface (AI Conductor)

### ISSUE THREAD

**Issue by iclyn-taero** [SEMOSS/community#2]
### Is your feature request related to a problem? Please describe.

Currently, chaining apps is a very technical process and everything needs to be written in the notebook. Add the ability for a user to use/interact with multiple apps through a general interface.

### Describe the solution you'd like

Process:
1. User asks a question into a chat box. 
2. This fires off a query to the llm engine which comes back with steps that align to individual apps to accomplish task.
3. Using the app description, it does a vector match to the description of the app
4. User sees list of steps mapped to apps to accomplish that specific step tasking.
4. User can add additional steps
5. If no app is available for a specific task, user can walk through steps to create one or have the system create one for them with more prompting information.
6. Renders a new app that could be saved if the user chooses to.

### Describe alternatives you've considered

Hand constructed via the notebook

### Additional context

N/A

### Tasks
- [x] Develop initial wireframes / UI prototype of the functionality. https://www.figma.com/design/vKalSnkXYGsFWKIlcfSArs/AI-Conductor?node-id=0-1
- [ ] Document payload, reactors needed, and workflow
- [ ] Create Reactor that finds a match of apps that will be used as steps
- [ ] Take App inputs and have ability to take those inputs and consume as an API
- [ ] [Prototype UI for AI Conductor](https://github.com/SEMOSS/semoss-ui/issues/219)

**Comment by neelneelneel** [comment]
Moved to https://github.com/SEMOSS/ai-conductor
