### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by johbaxter** [SEMOSS/community#24]
### Is your feature request related to a problem? Please describe.

How do we communicate to user that a reference of a variable has been deleted.  And what background logic should we take into account for this via a UX experience.

I delete query-sheet-a, but it is one of my variables.  What steps should we provide for them if that is the case.

Ask them whether they want to

Delete the variable?

OR

Switch the reference?

### Describe the solution you'd like

@natdink Will ask you to first think through this, as this is our immediate problem.  And then while doing this take a look at our adding variable process?  How can we make this better (you may already have wireframes).

### Tasks

- [ ] Keep track of block versions for rollbacks and ability to see the history of structure 
- [ ] UX deleting the reference of a variable
- [ ] 
- [ ] Migration logic to remove variables that reference value does not exist
