### ISSUE TITLE
[FEAT] Prompt Hub

### ISSUE THREAD

**Issue by johbaxter** [SEMOSS/community#27]
### Is your feature request related to a problem? Please describe.

This will first live in our Agent Builder, as a selection process when selecting a prompt.  

** Will likely need to store the prompt id on our structure that gets saved in App.JSON.  The reason for this, if the prompt changes we need to let our app know that the prompt has changed, and it should be reflected there as well.  But don't think to deep into this.

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Tasks

A list of individual tasks / issues that need to be completed before the ticket is resolved

- [ ] Create DB and BE CRUD reactors for a prompt
- [ ] Create a Prompt Hub for the management of prompts
- [ ] Add Prompts into our Agent Builder

**Comment by johbaxter** [comment]
GetPrompt(id) used to be able to reference from within app

ListPrompt --> we need an id to be used within the app

**Comment by johbaxter** [comment]
![image](https://github.com/user-attachments/assets/ff0184ac-34c5-4cec-8942-ca9cfb20790e)
