### ISSUE TITLE
[BUG] Bad Call When Landing on Engine Page from Settings with Admin Mode Enabled

### ISSUE THREAD

**Issue by iclyn-taero** [SEMOSS/community#3]
### A clear and concise description of what the issue is.
While in Admin Mode on the settings page, I open an engine that I do not have access to.  When I click settings for either -(function, storage, model, database, vector, and app) and look at the rest calls that are there.  One which is a `/getUserEnginePermission` that is not the admin endpoint and then another one  just below that, which is `/getProjectUsers` is the admin endpoint.  The `/getUserEnginePermission` should hit our admin endpoint just like `getProjectUsers`

#### How to reproduce the issue

1.  Login as admin
2.  Go to 'http://localhost:9090/semoss-ui/packages/client/dist/#/settings'
3.  Click on 'Admin Off' at top right to toggle your admin privilege
4.  Click on App Settings
5.  Open up dev tools and go to network
6.  Select an App that your current logged in user is not a registered member of (neither Author, Editor, Read-Only)
6a. If you are a member of the app select one of your apps and look at the Members table, just remove access for yourself
8.  Look at the failed HTTP request and see error

### Expected results
For this flow since you are an admin this should hit our admin route

-  From: http://localhost:9090/vha-supply/api/auth/project/getUserProjectPermission?projectId=11452f9f-ad7a-4853-9b6d-c03172ca20dd 
- To: http://localhost:9090/vha-supply/api/auth/**admin**/project/getUserProjectPermission?projectId=11452f9f-ad7a-4853-9b6d-c03172ca20dd

### Actual results
For this flow currently it hits our non-admin route

- http://localhost:9090/vha-supply/api/auth/project/getUserProjectPermission?projectId=11452f9f-ad7a-4853-9b6d-c03172ca20dd

### Screenshots
![Image](https://github.com/user-attachments/assets/3fd14b64-1641-46a1-8ddf-ef152b53a643)
![Image](https://github.com/user-attachments/assets/2165c358-6c24-4402-bd8f-423887248bb3)

### SEMOSS version
4.3.0-SNAPSHOT
2024-07-11 13:52:46

### Task
- [ ] SEMOSS/semoss-ui#207
- [ ] While in admin, we hit the correct admin endpoint
- [ ] While not an admin we do not hit our admin endpoint

### Additional context

- Every time the Settings page is re-rendered, Admin Mode is set to off
- configStore.store.user.admin is always set to true and never changes
- The getUserEnginePermission useEffect is unable to track admin Mode, getUserEnginePermission.status, nor getUserEnginePermission.data as even if you turn admin Mode on/off, the useEffect is never triggered.

**Comment by kyang4** [comment]
@johbaxter Did Paulson take care of this one too when doing the Access Page?
