### ISSUE TITLE
[FEAT] Split screen the App builder experience

### ISSUE THREAD

**Issue by natdink** [SEMOSS/community#30]
### Is your feature request related to a problem? Please describe.

I get frustrated when I am trying to build an app, specifically when I'm trying to link UI objects with data/code/variables in my data notebook. I find it cumbersome to have to move between two different pages and can never see the full picture as I test out my code between the user-facing UI and my data notebook.

### Describe the solution you'd like

A split screen view of the data and design pages so that they are side by side. Could provide a way to minimize each window but it is important to me that I see both in one view. I especially want to be able to see/access variables regardless of what view I'm looking at.

### Describe alternatives you've considered

We have previously considered a center panel which could open/close from below to link data cells on the design side in order to maintain the same left and right control bars. However, the need for the split screen has become so important to our users we don't think this is a valid stopgap.

### Tasks

A list of individual tasks / issues that need to be completed before the ticket is resolved

- [ ] SEMOSS/semoss-ui#313
- [ ] Prototype split screen in dev
- [ ] Build out the split screen based on Figma

**Comment by johbaxter** [comment]
Closed with redesign using golden layout
