### ISSUE TITLE
[FEAT] Enhance UX/UI of current response format (and general styling updates)

### ISSUE THREAD

**Issue by natdink** [SEMOSS/community#39]
### Describe the solution you'd like

Enhance the UX/UI of current response format and make general styling updates. 

### Additional context
See https://github.com/SEMOSS/community/issues/38

### Tasks
- [ ] Update Q&A description header copy
- [ ] Enhance response UI/UX layout in [Figma](https://www.figma.com/design/L3j6ululdlNZI4QvOrCeHA/Add-Vector-Flow?node-id=159-2634&t=fZycr9hBjLJwZu95-1)
- [ ] General styling updates....rounded corners not matching the two boxes, narrowed/fixed width ofthe control panel on left, etc
